package registry

import "ayayron/internal/models"

// All returns the complete hardcoded tool catalog.
func All() []models.Tool {
	return []models.Tool{
		// --- Core Tools ---
		{
			ID:           "git",
			Name:         "Git",
			Description:  "Distributed version control system",
			Category:     models.CategoryCore,
			CheckCmd:     "git --version",
			LinuxCmd:     "sudo apt-get install -y git",
			WindowsCmd:   "winget install Git.Git",
			RequiresSudo: true,
		},
		{
			ID:           "curl",
			Name:         "curl",
			Description:  "Command-line tool for transferring data with URLs",
			Category:     models.CategoryCore,
			CheckCmd:     "curl --version",
			LinuxCmd:     "sudo apt-get install -y curl",
			WindowsCmd:   "winget install cURL.cURL",
			RequiresSudo: true,
		},
		{
			ID:           "wget",
			Name:         "wget",
			Description:  "Network downloader",
			Category:     models.CategoryCore,
			CheckCmd:     "wget --version",
			LinuxCmd:     "sudo apt-get install -y wget",
			WindowsCmd:   "winget install GnuWin32.Wget",
			RequiresSudo: true,
		},
		{
			ID:           "vim",
			Name:         "Vim",
			Description:  "Terminal-based text editor",
			Category:     models.CategoryCore,
			CheckCmd:     "vim --version",
			LinuxCmd:     "sudo apt-get install -y vim",
			WindowsCmd:   "winget install vim.vim",
			RequiresSudo: true,
		},
		{
			ID:           "tmux",
			Name:         "tmux",
			Description:  "Terminal multiplexer — split, detach, persist sessions",
			Category:     models.CategoryCore,
			CheckCmd:     "tmux -V",
			LinuxCmd:     "sudo apt-get install -y tmux",
			WindowsCmd:   "",
			RequiresSudo: true,
		},
		{
			ID:           "htop",
			Name:         "htop",
			Description:  "Interactive process viewer",
			Category:     models.CategoryCore,
			CheckCmd:     "htop --version",
			LinuxCmd:     "sudo apt-get install -y htop",
			WindowsCmd:   "",
			RequiresSudo: true,
		},
		{
			ID:           "jq",
			Name:         "jq",
			Description:  "Command-line JSON processor",
			Category:     models.CategoryCore,
			CheckCmd:     "jq --version",
			LinuxCmd:     "sudo apt-get install -y jq",
			WindowsCmd:   "winget install jqlang.jq",
			RequiresSudo: true,
		},
		{
			ID:           "tree",
			Name:         "tree",
			Description:  "Directory listing in tree format",
			Category:     models.CategoryCore,
			CheckCmd:     "tree --version",
			LinuxCmd:     "sudo apt-get install -y tree",
			WindowsCmd:   "winget install GnuWin32.Tree",
			RequiresSudo: true,
		},
		{
			ID:           "make",
			Name:         "Make",
			Description:  "Build automation tool",
			Category:     models.CategoryCore,
			CheckCmd:     "make --version",
			LinuxCmd:     "sudo apt-get install -y make",
			WindowsCmd:   "winget install GnuWin32.Make",
			RequiresSudo: true,
		},
		// --- Languages ---
		{
			ID:          "nodejs",
			Name:        "Node.js (via nvm)",
			Description: "JavaScript runtime — nvm manages multiple Node versions",
			Category:    models.CategoryLanguages,
			CheckCmd:    "node --version",
			LinuxCmd: `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && ` +
				`export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm install --lts`,
			WindowsCmd:   "winget install CoreyButler.NVMforWindows",
			RequiresSudo: false,
		},
		{
			ID:           "python3",
			Name:         "Python 3",
			Description:  "Python programming language + pip + venv",
			Category:     models.CategoryLanguages,
			CheckCmd:     "python3 --version",
			LinuxCmd:     "sudo apt-get install -y python3 python3-pip python3-venv",
			WindowsCmd:   "winget install Python.Python.3",
			RequiresSudo: true,
		},
		{
			ID:          "golang",
			Name:        "Go",
			Description: "Go programming language",
			Category:    models.CategoryLanguages,
			CheckCmd:    "go version",
			LinuxCmd: `curl -Lo /tmp/go.tar.gz https://go.dev/dl/go1.23.linux-amd64.tar.gz && ` +
				`sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf /tmp/go.tar.gz && ` +
				`grep -qxF 'export PATH=$PATH:/usr/local/go/bin' ~/.bashrc || echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc`,
			WindowsCmd:   "winget install GoLang.Go",
			RequiresSudo: true,
		},
		{
			ID:          "rust",
			Name:        "Rust (via rustup)",
			Description: "Systems programming language — rustup manages toolchains",
			Category:    models.CategoryLanguages,
			CheckCmd:    "rustc --version",
			LinuxCmd:    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",
			WindowsCmd:  "winget install Rustlang.Rustup",
		},
		{
			ID:          "java",
			Name:        "Java (via SDKMAN)",
			Description: "Java Development Kit — SDKMAN manages JDK versions",
			Category:    models.CategoryLanguages,
			CheckCmd:    "java -version",
			LinuxCmd: `curl -s "https://get.sdkman.io" | bash && ` +
				`source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java`,
			WindowsCmd: "winget install EclipseAdoptium.Temurin.21.JDK",
		},
		// --- Databases ---
		{
			ID:           "postgresql",
			Name:         "PostgreSQL",
			Description:  "Advanced open-source relational database",
			Category:     models.CategoryDatabases,
			CheckCmd:     "psql --version",
			LinuxCmd:     "sudo apt-get install -y postgresql postgresql-contrib",
			WindowsCmd:   "winget install PostgreSQL.PostgreSQL",
			RequiresSudo: true,
		},
		{
			ID:           "mysql",
			Name:         "MySQL",
			Description:  "Popular open-source relational database",
			Category:     models.CategoryDatabases,
			CheckCmd:     "mysql --version",
			LinuxCmd:     "sudo apt-get install -y mysql-server",
			WindowsCmd:   "winget install Oracle.MySQL",
			RequiresSudo: true,
		},
		{
			ID:           "sqlite3",
			Name:         "SQLite3",
			Description:  "Self-contained, serverless SQL database engine",
			Category:     models.CategoryDatabases,
			CheckCmd:     "sqlite3 --version",
			LinuxCmd:     "sudo apt-get install -y sqlite3",
			WindowsCmd:   "winget install SQLite.SQLite",
			RequiresSudo: true,
		},
		{
			ID:           "redis",
			Name:         "Redis",
			Description:  "In-memory data structure store",
			Category:     models.CategoryDatabases,
			CheckCmd:     "redis-cli --version",
			LinuxCmd:     "sudo apt-get install -y redis-server",
			WindowsCmd:   "winget install Redis.Redis",
			RequiresSudo: true,
		},
		{
			ID:           "mongodb",
			Name:         "MongoDB",
			Description:  "Document-oriented NoSQL database",
			Category:     models.CategoryDatabases,
			CheckCmd:     "mongod --version",
			LinuxCmd: `curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg && ` +
				`echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | ` +
				`sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list && sudo apt-get update && sudo apt-get install -y mongodb-org`,
			WindowsCmd:   "winget install MongoDB.Server",
			RequiresSudo: true,
		},
		// --- Cloud & DevOps ---
		{
			ID:          "docker",
			Name:        "Docker",
			Description: "Container platform for building and running containers",
			Category:    models.CategoryCloud,
			CheckCmd:    "docker --version",
			LinuxCmd:    `curl -fsSL https://get.docker.com | sh && sudo usermod -aG docker $USER`,
			WindowsCmd:  "winget install Docker.DockerDesktop",
			RequiresSudo: true,
		},
		{
			ID:          "kubectl",
			Name:        "kubectl",
			Description: "Kubernetes command-line tool",
			Category:    models.CategoryCloud,
			CheckCmd:    "kubectl version --client",
			LinuxCmd: `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && ` +
				`sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl`,
			WindowsCmd:   "winget install Kubernetes.kubectl",
			RequiresSudo: true,
		},
		{
			ID:           "helm",
			Name:         "Helm",
			Description:  "Kubernetes package manager",
			Category:     models.CategoryCloud,
			CheckCmd:     "helm version",
			LinuxCmd:     "curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash",
			WindowsCmd:   "winget install Helm.Helm",
			RequiresSudo: false,
		},
		{
			ID:          "awscli",
			Name:        "AWS CLI",
			Description: "Amazon Web Services command-line interface",
			Category:    models.CategoryCloud,
			CheckCmd:    "aws --version",
			LinuxCmd: `curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && ` +
				`unzip -q /tmp/awscliv2.zip -d /tmp && sudo /tmp/aws/install`,
			WindowsCmd:   "winget install Amazon.AWSCLI",
			RequiresSudo: true,
		},
		{
			ID:          "terraform",
			Name:        "Terraform",
			Description: "Infrastructure as code by HashiCorp",
			Category:    models.CategoryCloud,
			CheckCmd:    "terraform --version",
			LinuxCmd: `wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && ` +
				`echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | ` +
				`sudo tee /etc/apt/sources.list.d/hashicorp.list && sudo apt-get update && sudo apt-get install -y terraform`,
			WindowsCmd:   "winget install Hashicorp.Terraform",
			RequiresSudo: true,
		},
		{
			ID:           "azure-cli",
			Name:         "Azure CLI",
			Description:  "Microsoft Azure command-line interface",
			Category:     models.CategoryCloud,
			CheckCmd:     "az --version",
			LinuxCmd:     "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash",
			WindowsCmd:   "winget install Microsoft.AzureCLI",
			RequiresSudo: true,
		},
		{
			ID:          "gcloud",
			Name:        "Google Cloud CLI",
			Description: "Google Cloud Platform command-line interface",
			Category:    models.CategoryCloud,
			CheckCmd:    "gcloud --version",
			LinuxCmd: `curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz && ` +
				`tar -xf google-cloud-cli-linux-x86_64.tar.gz -C $HOME && $HOME/google-cloud-sdk/install.sh --quiet`,
			WindowsCmd:   "winget install Google.CloudSDK",
			RequiresSudo: false,
		},
		// --- Editors ---
		{
			ID:          "vscode",
			Name:        "VS Code",
			Description: "Lightweight but powerful source code editor by Microsoft",
			Category:    models.CategoryEditors,
			CheckCmd:    "code --version",
			LinuxCmd: `wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg && ` +
				`sudo install -D -o root -g root -m 644 /tmp/packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg && ` +
				`echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | ` +
				`sudo tee /etc/apt/sources.list.d/vscode.list && sudo apt-get update && sudo apt-get install -y code`,
			WindowsCmd:   "winget install Microsoft.VisualStudioCode",
			RequiresSudo: true,
		},
		{
			ID:           "neovim",
			Name:         "Neovim",
			Description:  "Hyperextensible Vim-based text editor",
			Category:     models.CategoryEditors,
			CheckCmd:     "nvim --version",
			LinuxCmd:     "sudo apt-get install -y neovim",
			WindowsCmd:   "winget install Neovim.Neovim",
			RequiresSudo: true,
		},
		// --- Terminal ---
		{
			ID:           "zsh",
			Name:         "Zsh",
			Description:  "Extended Bourne shell with many improvements",
			Category:     models.CategoryTerminal,
			CheckCmd:     "zsh --version",
			LinuxCmd:     "sudo apt-get install -y zsh",
			WindowsCmd:   "",
			RequiresSudo: true,
		},
		{
			ID:          "ohmyzsh",
			Name:        "Oh My Zsh",
			Description: "Framework for managing your Zsh configuration",
			Category:    models.CategoryTerminal,
			CheckCmd:    "[ -d $HOME/.oh-my-zsh ]",
			LinuxCmd:    `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended`,
			WindowsCmd:  "",
		},
		{
			ID:           "starship",
			Name:         "Starship",
			Description:  "Cross-shell minimal and blazing-fast prompt",
			Category:     models.CategoryTerminal,
			CheckCmd:     "starship --version",
			LinuxCmd:     "curl -sS https://starship.rs/install.sh | sh -s -- --yes",
			WindowsCmd:   "winget install Starship.Starship",
			RequiresSudo: true,
		},
		{
			ID:           "fzf",
			Name:         "fzf",
			Description:  "Command-line fuzzy finder",
			Category:     models.CategoryTerminal,
			CheckCmd:     "fzf --version",
			LinuxCmd:     "sudo apt-get install -y fzf",
			WindowsCmd:   "winget install junegunn.fzf",
			RequiresSudo: true,
		},
		{
			ID:           "zoxide",
			Name:         "zoxide",
			Description:  "Smarter cd — learns your most-used directories",
			Category:     models.CategoryTerminal,
			CheckCmd:     "zoxide --version",
			LinuxCmd:     "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh",
			WindowsCmd:   "winget install ajeetdsouza.zoxide",
			RequiresSudo: false,
		},
		{
			ID:           "bat",
			Name:         "bat",
			Description:  "cat clone with syntax highlighting and Git integration",
			Category:     models.CategoryTerminal,
			CheckCmd:     "bat --version",
			LinuxCmd:     "sudo apt-get install -y bat",
			WindowsCmd:   "winget install sharkdp.bat",
			RequiresSudo: true,
		},
		{
			ID:           "eza",
			Name:         "eza",
			Description:  "Modern replacement for ls with icons and Git info",
			Category:     models.CategoryTerminal,
			CheckCmd:     "eza --version",
			LinuxCmd: `sudo apt-get install -y gpg && ` +
				`wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg && ` +
				`echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list && ` +
				`sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list && ` +
				`sudo apt-get update && sudo apt-get install -y eza`,
			WindowsCmd:   "winget install eza-community.eza",
			RequiresSudo: true,
		},
	}
}

// Profiles returns all preset tool bundles.
func Profiles() []models.Profile {
	return []models.Profile{
		{
			ID:      "minimal",
			Name:    "Minimal Dev",
			Icon:    "terminal",
			ToolIDs: []string{"git", "curl", "vim", "jq", "make"},
		},
		{
			ID:      "fullstack-js",
			Name:    "Full Stack JS",
			Icon:    "code",
			ToolIDs: []string{"git", "curl", "nodejs", "vscode", "docker", "postgresql"},
		},
		{
			ID:      "go-developer",
			Name:    "Go Developer",
			Icon:    "server",
			ToolIDs: []string{"git", "curl", "golang", "neovim", "docker", "postgresql", "tmux", "fzf"},
		},
		{
			ID:      "data-science",
			Name:    "Data Science",
			Icon:    "chart",
			ToolIDs: []string{"git", "curl", "python3", "vscode", "docker", "sqlite3", "jq"},
		},
	}
}
